# Lint my PRs 
name: Lint Pull Requests    
on: [push, workflow_dispatch]
jobs:    
  lint:
    name: Run Kube-Linter and output json sarif file
    runs-on: ubuntu-20.04 
    steps:
      - uses: actions/checkout@v2
      - name: Lint Repository 
        uses: jduimovich/kube-linter-action@main
        with:
          directory: deploy    
          outputFile: kube-linter.sarif
      - name: Show sarif
        run: |  
          cat kube-linter.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: kube-linter.sarif