# Lint my PRs 
name: Lint Pull Requests    
on: [pull_request, workflow_dispatch]
jobs:    
  lint:
    name: Run Kube-Linter and output json sarif file
    runs-on: ubuntu-20.04 
    steps:
      - uses: actions/checkout@v2
      - name: Lint Repository 
        uses: jduimovich/kube-linter-action@main
        with:
          directory: deploy    
          outputFile: kube-linter.out
      - name: Convert raw text to sarif 
        run: |  
          node convert.js kube-linter.out output.sarif  
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: output.sarif